[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[redirects]]
from = "https://kikuzukikai.netlify.com/*"
to = "https://www.kikuzukikai.org/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/404.html"
status = 404
force = false
