[build]
ignore = "git diff --quiet HEAD^ HEAD sub_dir/"

[[redirects]]
from = "https://kikuzukikai.netlify.com/*"
to = "https://www.kikuzukikai.org/:splat"
status = 301
force = true

[[headers]]
for = "/*"
[headers.values]
cache-control = "public, max-age=2592000"
