[build]
ignore = "git diff --quiet HEAD^ HEAD sub_dir/"
command = "npm run build"
functions = "api"

[[redirects]]
from = "https://kikuzukikai.netlify.com/*"
to = "https://www.kikuzukikai.org/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/portal/:splat"
status = 302
force = false
conditions = {Role = ["admin, guest"]}

# [[headers]]
# for = "/*"
# [headers.values]
# cache-control = "public, max-age=31536000"
