version: 2
jobs:
  build:
    docker:
      - image: starefossen/ruby-node: 2-10
    working_directory: ~/workspace
    steps:
      - checkout
      - run: gem update --system
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec jekyll build
      - run: firebase deploy --token=$FIREBASE_TOKEN
