version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby-node:2-10

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Ruby dependencies
          command: bundle install

      - run:
          name: Node dependencies
          command: npm install -g firebase-tools

      - run:
          name: Build
          command: bundle exec jekyll build

      - run:
          name: Deploy
          command: firebase deploy --token=$FIREBASE_TOKEN