version: 2
jobs:
  Bundle-Install:
    docker:
    - image: circleci/ruby:2.4
    steps:
    - run:
        name: Install bundle
        command: gem install bundler
  Jekyll-build:
    docker:
    - image: circleci/ruby:2.4
    steps:
    - checkout
    - run:
        name: Install rubygems
        command: bundle install
    - run:
        name: Build Jekyll
        command: bundle exec jekyll build
  Firebase-Install-and-Build:
    docker:
    - image: circleci/node:7.10
    steps:
    - checkout
    - run:
        name: Install Firebase tools if not installed
        command: npm install firebase-tools
    - run:
        name: Project Alias
        command: node_modules/.bin/firebase use default
    - run:
        name: Deploy to Firebase
        command: node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
  version: 2
  workflow:
    jobs:
    - Bundle-Install
    - Jekyll-build:
        requires:
        - Bundle-Install
    - Firebase-Install-and-Build:
        requires:
        - Jekyll-build