version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
    working_directory: ~/workspace
    steps:
      - checkout
      - run: gem update --system
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec jekyll build
